### ISSUE TITLE
incompatibility to be used with sonarqube

### ISSUE THREAD

**Issue by paramosr** [jenkinsci/osf-builder-suite-standalone-sonar-linter-plugin#1]
### Reproduction steps

When the OSF builder sonar linter is executed, it is supposed to generate a .json file to create a graphical report with the failures.
It generates correctly a json file but it is an array.
So, I try to use SonarQube (in the version of Warnings-ns plugin) and it's waitting for an json object file (not an array).
The problem is that the json file is created but is not compatible with Sonar (or others plugin), so is not very useful.

Any one would know what to do to solve this?

thanks,
Pablo.

**Comment by danechitoaie** [comment]
Unfortunately this plugin is no longer actively maintained. We have a different one for Sonar but it's developed internally and not open sourced/made available outside the company.
